[project]
name = "invisipic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bitarray>=3.4.2",
    "pillow>=11.2.1",
    "pycryptodome>=3.23.0",
    "pyinstaller>=6.14.1",
    "ttkbootstrap>=1.12.1",
]
